apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: gcr.io/kubecon-na-2018/skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: kubecon-na-2018
